core/urls.py
from django.urls import path

app_name = 'core'

from .views import *
urlpatterns = [
    path('',index,name="index"),
    path("pesan/", pesan, name="pesan"),
    path("listbus/", listbus, name="listbus"),
    path('pesan/cari/<track1>/<track2>/<bulan>/<tanggal>/<tahun>/',cari,name="cari"),
    path("pesan/beli_tiket/", beli_tiket, name="beli_tiket"),
    path("my_ticket/", my_ticket, name="my_ticket"),
    
    path('pdf/',pdf)
]

ticketingBus/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf.urls import handler404
from django.views.static import serve 

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('',include('core.urls',namespace="core")),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
  
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kiga - Tic</title>

    <link rel="icon" href=" {% static 'favicon_io/favicon.ico' %} " type="image/x-icon">
    <link rel="stylesheet" href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendor/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendor/jquery-steps/jquery.steps.css' %}">
    


    <link rel="stylesheet" href="{% static 'assets/vendor/animate-css/vivify.min.css' %}">
    
    <link rel="stylesheet" href="{% static 'assets/vendor/bootstrap-multiselect/bootstrap-multiselect.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendor/bootstrap-datepicker/css/bootstrap-datepicker3.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendor/bootstrap-colorpicker/css/bootstrap-colorpicker.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendor/multi-select/css/multi-select.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendor/nouislider/nouislider.min.css' %}">
    




    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{% static 'assets/site.min.css' %}">
    
</head>
<body class="theme-cyan ">
    <!-- <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 mr-auto">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'core:pesan' %}">Booking ?</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
      <br> -->
      <br>
      
    <div class="container">
      
      {% block content %}
        
      {% endblock content %}
        

    </div>



<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>		
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script src="{% static 'assets/bundles/libscripts.bundle.js' %}"></script>    
<script src="{% static 'assets/bundles/vendorscripts.bundle.js' %}"></script>

<script src="{% static 'assets/vendor/jquery-validation/jquery.validate.js' %}"></script><!-- Jquery Validation Plugin Css -->
<script src="{% static 'assets/vendor/jquery-steps/jquery.steps.js' %}"></script><!-- JQuery Steps Plugin Js -->
<script src="{% static 'assets/bundles/mainscripts.bundle.js' %}"></script>
<script src="{% static 'assets/js/pages/forms/form-wizard.js' %}"></script>


<script src="{% static 'assets/vendor/bootstrap-colorpicker/js/bootstrap-colorpicker.js' %}"></script><!-- Bootstrap Colorpicker Js --> 
<script src="{% static 'assets/vendor/jquery-inputmask/jquery.inputmask.bundle.js' %}"></script><!-- Input Mask Plugin Js --> 
<script src="{% static 'assets/vendor/jquery.maskedinput/jquery.maskedinput.min.js' %}"></script>
<script src="{% static 'assets/vendor/multi-select/js/jquery.multi-select.js' %}"></script><!-- Multi Select Plugin Js -->
<script src="{% static 'assets/vendor/bootstrap-multiselect/bootstrap-multiselect.js' %}"></script>
<script src="{% static 'assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>
<script src="{% static 'assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput.js' %}"></script><!-- Bootstrap Tags Input Plugin Js --> 
<script src="{% static 'assets/vendor/nouislider/nouislider.js' %}"></script><!-- noUISlider Plugin Js -->
<script src="{% static 'assets/bundles/mainscripts.bundle.js' %}"></script>
<script src="{% static 'assets/js/pages/forms/advanced-form-elements.js' %}"></script>
</body>
</html>

templates/list.html
{% extends 'base.html' %}



{% block content %}
    <h1 style="color: black;">List Bus</h1>
    <br>
    <br>
    {% for bs in bus %}
        


    <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="{{bs.img.url}}" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">{{bs.platNo}}</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>


    {% endfor %}
        



{% endblock content %}
    

templates/my_ticket.html
{% extends 'base.html' %}




{% block content %}
<h1>
  My Ticket 
</h1>
<table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">No </th>
        <th scope="col">Name</th>
        <th scope="col">Date</th>
        <th scope="col">Seat</th>
        <th scope="col">Bus</th>
        <th scope="col">Expire At</th>
        
      </tr>
    </thead>
    <tbody>
        {% for i,x in solve %}
        
        {% if x == "Expire" %}
        <tr class="bg-orange text-light">
          {% else %}
          
          {% if x <= 5 and x > 0 %}
          <tr class="bg-cyan text-light">
            {% elif x <= 10 and x > 5 %}

            <tr class="bg-blue text-light">
          {% endif %}
        {% endif %}
          
        <th scope="row">{{forloop.counter }}</th>
        <td >{{i.nama}}</td>
        <td>{{i.tanggal}}</td>
        <td>{{i.kursi}}</td>
        <td>{{i.bus}}</td>
        <td>{{x}}</td>
      </tr>
      {% endfor %}
      
    </tbody>
  </table>
  
      <div class="card">

        <h1>Bukti pembayaran</h1>
        <h2>{{data.user.username}}</h2>
        <h2>total harga :{{data.total_harga}}</h2>
      </div>  

<!-- 
                 <div class="body">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>First Name</th>
                                            <th>Last Name</th>
                                            <th>Class name</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr class="bg-blue text-light">
                                            <th scope="row">1</th>
                                            <td>Mark</td>
                                            <td>Otto</td>
                                            <td>.bg-blue</td>
                                        </tr>
                                        <tr class="bg-cyan text-light">
                                            <th scope="row">2</th>
                                            <td>Jacob</td>
                                            <td>Thornton</td>
                                            <td>.bg-cyan</td>
                                        </tr>
                                        <tr class="bg-orange text-light">
                                            <th scope="row">3</th>
                                            <td>Larry</td>
                                            <td>the Bird</td>
                                            <td>.bg-orange</td>
                                        </tr>
                                        <tr class="bg-pink text-light">
                                            <th scope="row">4</th>
                                            <td>Larry</td>
                                            <td>Jellybean</td>
                                            <td>.bg-pink</td>
                                        </tr>
                                        <tr class="bg-purple text-light">
                                            <th scope="row">5</th>
                                            <td>Larry</td>
                                            <td>Kikat</td>
                                            <td>.bg-purple</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <h6 class="m-t-30">First Column background</h6>
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>First Name</th>
                                            <th>Last Name</th>
                                            <th>Class name</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td class="bg-blue text-light">1</td>
                                            <td>Mark</td>
                                            <td>Otto</td>
                                            <td>.bg-blue</td>
                                        </tr>
                                        <tr>
                                            <td class="bg-cyan text-light">2</td>
                                            <td>Jacob</td>
                                            <td>Thornton</td>
                                            <td>.bg-cyan</td>
                                        </tr>
                                        <tr>
                                            <td class="bg-orange text-light">3</td>
                                            <td>Larry</td>
                                            <td>the Bird</td>
                                            <td>.bg-orange</td>
                                        </tr>
                                        <tr>
                                            <td class="bg-pink text-light">4</td>
                                            <td>Larry</td>
                                            <td>Jellybean</td>
                                            <td>.bg-pink</td>
                                        </tr>
                                        <tr>
                                            <td class="bg-purple text-light">5</td>
                                            <td>Larry</td>
                                            <td>Kikat</td>
                                            <td>.bg-purple</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div> -->
{% endblock content %}
    

templates/mytemplate.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>Title</title>
        <style type="text/css">
            body {
                font-weight: 200;
                font-size: 14px;
            }
            .header {
                font-size: 20px;
                font-weight: 100;
                text-align: center;
                color: #007cae;
            }
            .title {
                font-size: 22px;
                font-weight: 100;
               /* text-align: right;*/
               padding: 10px 20px 0px 20px;  
            }
            .title span {
                color: #007cae;
            }
            .details {
                padding: 10px 20px 0px 20px;
                text-align: left !important;
                /*margin-left: 40%;*/
            }
            .hrItem {
                border: none;
                height: 1px;
                /* Set the hr color */
                color: #333; /* old IE */
                background-color: #fff; /* Modern Browsers */
            }
        </style>
    </head>
    <body>
        <div class='wrapper'>
            <div class='header'>
                <p class='title'>Invoice # </p>
            </div>
        <div>
        <div class='details'>
            Bill to: <br/>{{invoice_id}}
            Amount:  <br/>
            Date: 
            <hr class='hrItem' />
        </div>
    </div>
    </body>
</html>

templates/pesan.html
{% extends 'base.html' %}



{% block content %}
<style>
    div label input {
   margin-right:100px;
}
body {
    font-family:sans-serif;
}

.ck-button1 {
    margin:4px;
    background-color:orange;
    border-radius:4px;
    border:1px solid orange;
    overflow:auto;
    float:left;
}
.ck-button {
    margin:4px;
    background-color:#EFEFEF;
    border-radius:4px;
    border:1px solid #D0D0D0;
    overflow:auto;
    float:left;
}

#ck-button label {
    float:left;
    width:4.0em;
}

#ck-button label span {
    text-align:center;
    padding:3px 0px;
    display:block;
    border-radius:4px;
}

#ck-button label input {
    position:absolute;
    top:-20px;
}

#ck-button input:hover + span {
    background-color:#efE0E0;
}

#ck-button input:checked + span {
    background-color:green;
    color:#fff;
}

#ck-button input:checked:hover + span {
    background-color:rgb(7, 179, 7);
    color:#fff;
}



#ck-button1 label {
    float:left;
    width:4.0em;
}

#ck-button1 label span {
    text-align:center;
    padding:3px 0px;
    display:block;
    border-radius:4px;
}

#ck-button1 label input {
    position:absolute;
    top:-20px;
}

#ck-button1 input:hover + span {
    background-color:#efE0E0;
}

#ck-button1 input:checked + span {
    background-color:green;
    color:#fff;
}

#ck-button1 input:checked:hover + span {
    background-color:rgb(7, 179, 7);;
    color:#fff;
}
</style>
    <h1 style="color: black;font-weight: bold;">Pesan</h1>
   


<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="card">
            <div class="header">
                <h2>form ticketing</h2>
                <ul class="header-dropdown dropdown">
                    
                    <li><a href="javascript:void(0);" class="full-screen"><i class="icon-frame"></i></a></li>
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"></a>
                        <ul class="dropdown-menu">
                            <li><a href="javascript:void(0);">Action</a></li>
                            <li><a href="javascript:void(0);">Another Action</a></li>
                            <li><a href="javascript:void(0);">Something else</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            
            <div  class="body wizard_validation">
                <form id="wizard_with_validation" method="POST">
                    {% csrf_token %}
                    <h3>Orderer information</h3>
                    <fieldset style="width: 100%;height: 100%;">
                        <div class="row clearfix">

                            <div style="width: 100%;margin: 0 auto;"> 
                                <center>
                            <select id="track1" name="track1 *" style="width: 45%;margin-left: 2%;" class="form-select" aria-label="Track1" required>
                                <option value="" selected>Dari ?</option>
                            {% for dt in track1 %}
                                <option value="{{dt}}">{{dt}}</option>
                                {% endfor %}
                                
                            </select>
                        
                            <select name="track2 *" id="track2" style="width: 45%;margin-right: 2%;" class="form-select" aria-label="Default select example" required>
                                <option value=""  selected>Ke ?</option>
                            {% for dt in track2 %}
                                <option value="{{dt}}">{{dt}}</option>
                                {% endfor %}
                                
                            </select>   
                        </center>
                        </div>
                   <div style="width: 100%; padding: 20px;">
                                <div class="form-group">
                                    <input type="text" name="nama" placeholder="Nama *" class="form-control" required>
                                </div>
                            
                   
                                <div class="input-group mb-3">
                                    <input name="tanggal" placeholder="Tanggal Keberangkatan *" data-provide="datepicker" data-date-autoclose="true" class="form-control">
                                </div>
                            </div>
                        </div>
                    </fieldset>
                    <h3>Taking A Seat</h3>


                   



                    <fieldset  style="width: 100%; overflow: auto;height: 100%;">
                        <div id="busList">

                        </div>
                        
                    </fieldset>
                    <h3>Terms Conditions !</h3>
                    <fieldset style="width: 100%;height: 100%;">
                        <div class="col-lg-12 col-md-12 col-sm-12">
                            <ul>
                                <h5><li>Payment no later than 1 day before departure </li></h5>
                                <h5><li>by agreeing to this means you agree to your responsibility as a consumer</li></h5>
                            </ul>
                        </div>
                        <div class="form-group">
                            <div class="fancy-checkbox">
                                <h5> <label><input type="checkbox" id="acceptTerms" name="acceptTerms"><span>I agree with the Terms and Conditions.</span></label></h5>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
       
        </div>
    </div>
</div>

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
{% endblock content %}
    